all: p1 p2 p3 p4 p5 p6

p1: p1-expr.cc
	g++ -o p1 p1-expr.cc
	
p2: p2-blk.cc
	g++ -o p2 p2-blk.cc
	
p3: p3-ops.cc
	g++ -o p3 p3-ops.cc
	
p4: p4-stdio.cc
	g++ -o p4 p4-stdio.cc
	
p5: p5-pass.cc
	g++ -o p5 p5-pass.cc
	
p6: p6-ref.cc
	g++ -o p6 p6-ref.cc
	
clean:
	rm -f p1 p2 p3 p4 p5 p6
